services:
  s3-protosearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s3-protosearch
    restart: always
    env_file:
      - .env
    volumes:
      - /sharepoint:/sharepoint:ro
      - /db:/db